<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="AJITH" name="org.rerunFBWithOutknownFailed.FbLogin" tests="6" failures="1" timestamp="10 Apr 2022 05:08:49 GMT" time="64.518" errors="0">
  <testcase name="t2" time="9.751" classname="org.rerunFBWithOutknownFailed.FbLogin">
    <skipped/>
  </testcase> <!-- t2 -->
  <testcase name="t2" time="7.050" classname="org.rerunFBWithOutknownFailed.FbLogin">
    <skipped/>
  </testcase> <!-- t2 -->
  <testcase name="t2" time="8.826" classname="org.rerunFBWithOutknownFailed.FbLogin">
    <skipped/>
  </testcase> <!-- t2 -->
  <testcase name="t1" time="11.813" classname="org.rerunFBWithOutknownFailed.FbLogin"/>
  <testcase name="t2" time="11.751" classname="org.rerunFBWithOutknownFailed.FbLogin">
    <skipped/>
  </testcase> <!-- t2 -->
  <testcase name="t2" time="15.327" classname="org.rerunFBWithOutknownFailed.FbLogin">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.rerunFBWithOutknownFailed.FbLogin.t2(FbLogin.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- t2 -->
</testsuite> <!-- org.rerunFBWithOutknownFailed.FbLogin -->
