<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="AJITH" name="org.test1.SoftAssert" tests="8" failures="0" timestamp="30 Mar 2022 12:14:38 GMT" time="27.236" errors="1">
  <testcase name="test6" time="4.734" classname="org.test1.SoftAssert"/>
  <testcase name="test5" time="2.416" classname="org.test1.SoftAssert"/>
  <testcase name="test3" time="2.484" classname="org.test1.SoftAssert">
    <error type="java.lang.Error" message="Unresolved compilation problem: 
	s cannot be resolved to a type
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
s cannot be resolved to a type

at org.test1.SoftAssert.test3(SoftAssert.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="7.496" classname="org.test1.SoftAssert"/>
  <testcase name="test4" time="2.641" classname="org.test1.SoftAssert"/>
  <testcase name="test4" time="2.485" classname="org.test1.SoftAssert"/>
  <testcase name="test4" time="2.678" classname="org.test1.SoftAssert"/>
  <testcase name="test4" time="2.302" classname="org.test1.SoftAssert"/>
</testsuite> <!-- org.test1.SoftAssert -->
